function acc = evaluate_accuracy(prediction, testLabel, objective_label)
acc = sum(prediction(find(testLabel == objective_label)) == ...
    testLabel(find(testLabel == objective_label))) ...
    /sum(testLabel == objective_label);
end